Repository Azure/azure-sdk-for-rust, pull requests merged in 2025-03, with the labels that each got.

#2258 Improve CONTRIBUTING.md
  CONTRIBUTING.md
  sdk/core/azure_core_test/README.md
Labels: Azure.Core

#2265 Generate seeded random test strings
  .vscode/cspell.json
  Cargo.lock
  sdk/core/azure_core_test/Cargo.toml
  sdk/core/azure_core_test/src/recording.rs
Labels: Azure.Core

#2267 Sync eng/common directory with azure-sdk-tools for PR 9955
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#2246 [Storage] `ContainerClient` (`create_container`, `delete_container`) and `BlobClient` (`download_blob`, `upload_blob`)
  eng/emitter-package-lock.json
  eng/emitter-package.json
  sdk/storage/assets.json
  sdk/storage/azure_storage_blob/src/clients/blob_client.rs
  sdk/storage/azure_storage_blob/src/clients/blob_container_client.rs
  sdk/storage/azure_storage_blob/src/generated/clients/blob_append_blob_client.rs
  sdk/storage/azure_storage_blob/src/generated/clients/blob_blob_client.rs
  sdk/storage/azure_storage_blob/src/generated/clients/blob_block_blob_client.rs
  sdk/storage/azure_storage_blob/src/generated/clients/blob_client.rs
  sdk/storage/azure_storage_blob/src/generated/clients/blob_container_client.rs
  sdk/storage/azure_storage_blob/src/generated/clients/blob_page_blob_client.rs
  sdk/storage/azure_storage_blob/src/generated/clients/blob_service_client.rs
  sdk/storage/azure_storage_blob/src/generated/clients/internal_models.rs
  sdk/storage/azure_storage_blob/src/generated/clients/method_options.rs
  sdk/storage/azure_storage_blob/src/generated/clients/mod.rs
  sdk/storage/azure_storage_blob/src/generated/enums.rs
  sdk/storage/azure_storage_blob/src/generated/mod.rs
  sdk/storage/azure_storage_blob/src/generated/models.rs
  sdk/storage/azure_storage_blob/src/lib.rs
  sdk/storage/azure_storage_blob/tests/blob_client.rs
  sdk/storage/azure_storage_blob/tests/blob_container_client.rs
  sdk/storage/azure_storage_blob/tsp-location.yaml
Labels: Storage

#2268 Sync eng/common directory with azure-sdk-tools for PR 9945
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#2276 Sync eng/common directory with azure-sdk-tools for PR 9963
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2266 Add ClientAssertionCredential
  sdk/identity/azure_identity/README.md
  sdk/identity/azure_identity/src/credentials/client_assertion_credentials.rs
  sdk/identity/azure_identity/src/credentials/mod.rs
  sdk/identity/azure_identity/src/credentials/workload_identity_credentials.rs
Labels: Azure.Identity, Community Contribution, customer-reported

#2275 Fixed #1976 - fe2o3-amqp should be fe2o3_amqp
  Cargo.lock
  sdk/core/azure_core_amqp/Cargo.toml
  sdk/core/azure_core_amqp/src/cbs.rs
  sdk/core/azure_core_amqp/src/connection.rs
  sdk/core/azure_core_amqp/src/lib.rs
  sdk/core/azure_core_amqp/src/management.rs
  sdk/core/azure_core_amqp/src/messaging.rs
  sdk/core/azure_core_amqp/src/receiver.rs
  sdk/core/azure_core_amqp/src/sender.rs
  sdk/core/azure_core_amqp/src/session.rs
  sdk/core/azure_core_amqp/src/value.rs
Labels: Azure.Core

#2252 [cosmos] use version-only references to avoid broken publish rewriting
  Cargo.lock
  eng/scripts/Language-Settings.ps1
  sdk/cosmos/azure_data_cosmos/CHANGELOG.md
  sdk/cosmos/azure_data_cosmos/Cargo.toml
Labels: Cosmos

#2285 Sync eng/common directory with azure-sdk-tools for PR 9982
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#2279 Sync eng/common directory with azure-sdk-tools for PR 9918
  eng/common/scripts/job-matrix/pullrequest-faq.md
Labels: EngSys, Central-EngSys

#2261 Sync eng/common directory with azure-sdk-tools for PR 9943
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2294 Bump versions and simplify dependencies
  Cargo.lock
  Cargo.toml
  eng/dict/crates.txt
  eng/scripts/Analyze-Code.ps1
  eng/scripts/Pack-Crates.ps1
  eng/scripts/Publish-Crates.ps1
  sdk/core/azure_core/Cargo.toml
  sdk/core/azure_core_amqp/Cargo.toml
  sdk/core/azure_core_test_macros/Cargo.toml
  sdk/cosmos/azure_data_cosmos/Cargo.toml
  sdk/eventhubs/azure_messaging_eventhubs/Cargo.toml
  sdk/identity/azure_identity/Cargo.toml
  sdk/keyvault/azure_security_keyvault_keys/Cargo.toml
  sdk/keyvault/azure_security_keyvault_secrets/Cargo.toml
  sdk/storage/azure_storage_blob/Cargo.toml
  sdk/typespec/Cargo.toml
  sdk/typespec/typespec_client_core/Cargo.toml
  sdk/typespec/typespec_macros/Cargo.toml
  sdk/typespec/typespec_macros/tests/compilation-tests.rs
  sdk/typespec/typespec_macros/tests/data/compilation-tests/.gitignore
  sdk/typespec/typespec_macros/tests/data/compilation-tests/Cargo.lock
  sdk/typespec/typespec_macros/tests/data/compilation-tests/Cargo.toml
Labels: Cosmos, Storage, Azure.Identity, Azure.Core

#2288 Automatically acquire test-proxy
  .gitignore
  .vscode/cspell.json
  Cargo.lock
  Cargo.toml
  eng/dict/crates.txt
  sdk/core/azure_core_test/Cargo.toml
  sdk/core/azure_core_test/src/proxy/bootstrap.rs
  sdk/core/azure_core_test/src/proxy/mod.rs
Labels: Azure.Core

#2308 Sync eng/common directory with azure-sdk-tools for PR 10013
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2307 Fix versions for pack and improve logs
  eng/scripts/Get-PackageDependencies.ps1
  eng/scripts/Pack-Crates.ps1
  sdk/core/azure_core_amqp/Cargo.toml
  sdk/eventhubs/azure_messaging_eventhubs/Cargo.toml
  sdk/template/azure_template/Cargo.toml
Labels: Azure.Core

#2189 Enable autobaselining only for `rust - core`
  .config/1espt/PipelineAutobaseliningConfig.yml
  .config/guardian/.gdnbaselines
  eng/pipelines/templates/stages/1es-redirect.yml
  eng/pipelines/templates/stages/archetype-sdk-client.yml
Labels: Azure.Core

#2306 Add AzurePipelinesCredential
  .vscode/settings.json
  Cargo.lock
  sdk/core/azure_core_test/Cargo.toml
  sdk/core/azure_core_test/src/credential.rs
  sdk/core/azure_core_test/src/credentials.rs
  sdk/core/azure_core_test/src/http/clients.rs
  sdk/core/azure_core_test/src/http/mod.rs
  sdk/core/azure_core_test/src/lib.rs
  sdk/core/azure_core_test/src/recording.rs
  sdk/identity/azure_identity/CHANGELOG.md
  sdk/identity/azure_identity/Cargo.toml
  sdk/identity/azure_identity/README.md
  sdk/identity/azure_identity/examples/specific_credential.rs
  sdk/identity/azure_identity/src/azure_pipelines_credential.rs
  sdk/identity/azure_identity/src/credentials/client_assertion_credentials.rs
  sdk/identity/azure_identity/src/credentials/default_azure_credentials.rs
  sdk/identity/azure_identity/src/credentials/mod.rs
  sdk/identity/azure_identity/src/credentials/options.rs
  sdk/identity/azure_identity/src/credentials/workload_identity_credentials.rs
  sdk/identity/azure_identity/src/federated_credentials_flow/mod.rs
  sdk/identity/azure_identity/src/lib.rs
Labels: Azure.Identity, Azure.Core

#2317 Sync eng/common directory with azure-sdk-tools for PR 9993
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2309 Add ChainedTokenCredential
  sdk/identity/azure_identity/src/chained_token_credential.rs
  sdk/identity/azure_identity/src/credentials/mod.rs
  sdk/identity/azure_identity/src/lib.rs
Labels: Azure.Identity

#2320 Remove builders from typespec_client_core
  sdk/core/azure_core/src/options/mod.rs
  sdk/typespec/typespec_client_core/src/date/mod.rs
  sdk/typespec/typespec_client_core/src/http/models/etag.rs
  sdk/typespec/typespec_client_core/src/http/options/builders.rs
  sdk/typespec/typespec_client_core/src/http/options/mod.rs
Labels: Azure.Identity, Azure.Core

#2324 Sync eng/common directory with azure-sdk-tools for PR 10030
  eng/common/pipelines/templates/steps/detect-api-changes.yml
Labels: EngSys, Central-EngSys

#2273 [Storage] `stage_block`, `commit_block_list` for `BlobClient`, `get_container_properties` for `ContainerClient`, `ServiceClient`
  .vscode/cspell.json
  Cargo.lock
  Cargo.toml
  sdk/storage/.dict.txt
  sdk/storage/assets.json
  sdk/storage/azure_storage_blob/Cargo.toml
  sdk/storage/azure_storage_blob/src/clients/blob_client.rs
  sdk/storage/azure_storage_blob/src/clients/blob_container_client.rs
  sdk/storage/azure_storage_blob/src/clients/blob_service_client.rs
  sdk/storage/azure_storage_blob/src/clients/mod.rs
  sdk/storage/azure_storage_blob/src/lib.rs
  sdk/storage/azure_storage_blob/src/models/container_properties.rs
  sdk/storage/azure_storage_blob/src/pipeline/mod.rs
  sdk/storage/azure_storage_blob/tests/blob_client.rs
  sdk/storage/azure_storage_blob/tests/blob_container_client.rs
  sdk/storage/azure_storage_blob/tests/blob_service_client.rs
  sdk/storage/azure_storage_blob_test/Cargo.toml
  sdk/storage/azure_storage_blob_test/src/lib.rs
Labels: Storage

#2326 Sync eng/common directory with azure-sdk-tools for PR 10028
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2321 Sync eng/common directory with azure-sdk-tools for PR 10027
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2328 Add async command executor
  Cargo.lock
  Cargo.toml
  eng/dict/crates.txt
  sdk/core/azure_core/CHANGELOG.md
  sdk/core/azure_core/Cargo.toml
  sdk/core/azure_core/src/lib.rs
  sdk/core/azure_core/src/process/mod.rs
  sdk/core/azure_core/src/process/standard.rs
  sdk/core/azure_core/src/process/tokio.rs
  sdk/identity/azure_identity/CHANGELOG.md
  sdk/identity/azure_identity/Cargo.toml
  sdk/identity/azure_identity/examples/azure_cli_credentials.rs
  sdk/identity/azure_identity/examples/specific_credential.rs
  sdk/identity/azure_identity/src/credentials/azure_cli_credentials.rs
  sdk/identity/azure_identity/src/credentials/cache.rs
  sdk/identity/azure_identity/src/credentials/default_azure_credentials.rs
  sdk/identity/azure_identity/src/credentials/options.rs
  sdk/identity/azure_identity/src/lib.rs
Labels: Azure.Identity, Azure.Core

#2329 Sync eng/common directory with azure-sdk-tools for PR 10039
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#2332 Sync eng/common directory with azure-sdk-tools for PR 10041
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#2338 Sync eng/common directory with azure-sdk-tools for PR 10046
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#2333 Add Content-Length for AzurePipelinesCredential
  sdk/identity/azure_identity/src/azure_pipelines_credential.rs
Labels: Azure.Identity

#2335 Sync eng/common directory with azure-sdk-tools for PR 10045
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#2339 Sync .github/workflows directory with azure-sdk-tools for PR 10054
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#2341 Subscribe to traces for live tests
  sdk/core/azure_core_test/src/recorded.rs
Labels: Azure.Core

#2334 Update Cosmos tests to be record/replay tests
  .devcontainer/devcontainer.json
  .devcontainer/oncreate
  .vscode/cspell.json
  sdk/cosmos/assets.json
  sdk/cosmos/azure_data_cosmos/tests/cosmos_containers.rs
  sdk/cosmos/azure_data_cosmos/tests/cosmos_databases.rs
  sdk/cosmos/azure_data_cosmos/tests/cosmos_items.rs
  sdk/cosmos/azure_data_cosmos/tests/cosmos_query.rs
  sdk/cosmos/azure_data_cosmos/tests/framework/test_account.rs
Labels: Cosmos

#2347 Sync eng/common directory with azure-sdk-tools for PR 10081
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#2375 Sync eng/common directory with azure-sdk-tools for PR 10096
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2376 Sync eng/common directory with azure-sdk-tools for PR 10100
  eng/common/pipelines/templates/stages/archetype-spec-gen-sdk.yml
Labels: EngSys, Central-EngSys

#2374 Optionally disable test tracing colors
  sdk/core/azure_core_test/README.md
  sdk/core/azure_core_test/src/recorded.rs
Labels: Azure.Core

#2367 Document features for docs.rs
  Cargo.toml
  sdk/core/azure_core/Cargo.toml
  sdk/core/azure_core/src/lib.rs
  sdk/core/azure_core_amqp/Cargo.toml
  sdk/core/azure_core_amqp/src/lib.rs
  sdk/eventhubs/azure_messaging_eventhubs/Cargo.toml
  sdk/eventhubs/azure_messaging_eventhubs/src/lib.rs
  sdk/identity/azure_identity/Cargo.toml
  sdk/identity/azure_identity/src/lib.rs
  sdk/typespec/Cargo.toml
  sdk/typespec/src/lib.rs
  sdk/typespec/typespec_client_core/Cargo.toml
  sdk/typespec/typespec_client_core/src/lib.rs
Labels: Azure.Identity, Azure.Core

#2386 Sync eng/common directory with azure-sdk-tools for PR 10129
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#2368 Sync eng/common directory with azure-sdk-tools for PR 10099
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#2385 Remove TokenCredential::clear_cache
  sdk/core/azure_core/CHANGELOG.md
  sdk/core/azure_core/src/credentials.rs
  sdk/core/azure_core_test/src/credentials.rs
  sdk/cosmos/azure_data_cosmos/src/pipeline/authorization_policy.rs
  sdk/identity/azure_identity/CHANGELOG.md
  sdk/identity/azure_identity/examples/specific_credential.rs
  sdk/identity/azure_identity/src/azure_pipelines_credential.rs
  sdk/identity/azure_identity/src/chained_token_credential.rs
  sdk/identity/azure_identity/src/credentials/app_service_managed_identity_credential.rs
  sdk/identity/azure_identity/src/credentials/azure_cli_credentials.rs
  sdk/identity/azure_identity/src/credentials/cache.rs
  sdk/identity/azure_identity/src/credentials/client_assertion_credentials.rs
  sdk/identity/azure_identity/src/credentials/client_certificate_credentials.rs
  sdk/identity/azure_identity/src/credentials/default_azure_credentials.rs
  sdk/identity/azure_identity/src/credentials/imds_managed_identity_credentials.rs
  sdk/identity/azure_identity/src/credentials/virtual_machine_managed_identity_credential.rs
  sdk/identity/azure_identity/src/credentials/workload_identity_credentials.rs
Labels: Cosmos, Azure.Identity, Azure.Core

#2389 Remove parsing module
  sdk/core/azure_core/CHANGELOG.md
  sdk/core/azure_core/src/lib.rs
  sdk/typespec/typespec_client_core/CHANGELOG.md
  sdk/typespec/typespec_client_core/src/lib.rs
  sdk/typespec/typespec_client_core/src/macros.rs
  sdk/typespec/typespec_client_core/src/parsing.rs
Labels: Azure.Core

#2391 Sync eng/common directory with azure-sdk-tools for PR 10135
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#2398 Improve error handling in Proxy startup and adjust executable path for Windows
  sdk/core/azure_core_test/src/proxy/bootstrap.rs
  sdk/core/azure_core_test/src/proxy/mod.rs
Labels: Azure.Core

#2403 Rename "operation" to "poller"
  sdk/core/azure_core/CHANGELOG.md
  sdk/core/azure_core/src/http/mod.rs
  sdk/core/azure_core/src/http/poller.rs
Labels: Azure.Core

#2404 Sync eng/common directory with azure-sdk-tools for PR 10004
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#2400 Sync eng/common directory with azure-sdk-tools for PR 10145
  eng/common/pipelines/templates/jobs/generate-job-matrix.yml
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#2412 Always ignore certain headers and sanitizers
  sdk/core/azure_core_test/src/proxy/bootstrap.rs
  sdk/core/azure_core_test/src/proxy/client.rs
  sdk/core/azure_core_test/src/proxy/matchers.rs
  sdk/core/azure_core_test/src/proxy/mod.rs
  sdk/core/azure_core_test/src/proxy/sanitizers.rs
  sdk/core/azure_core_test/src/recorded.rs
  sdk/core/azure_core_test/src/recording.rs
  sdk/cosmos/azure_data_cosmos/tests/framework/test_account.rs
  sdk/keyvault/azure_security_keyvault_keys/tests/key_client.rs
  sdk/keyvault/azure_security_keyvault_secrets/tests/secret_client.rs
Labels: Cosmos, Azure.Core

#2406 Add `x-ms-client-request-id` pipeline policy
  .vscode/cspell.json
  Cargo.lock
  sdk/core/azure_core/CHANGELOG.md
  sdk/core/azure_core/Cargo.toml
  sdk/core/azure_core/src/http/options/telemetry.rs
  sdk/core/azure_core/src/http/pipeline.rs
  sdk/core/azure_core/src/http/policies/client_request_id.rs
  sdk/core/azure_core/src/http/policies/mod.rs
  sdk/core/azure_core/src/http/policies/telemetry.rs
  sdk/core/azure_core/src/http/request/options/mod.rs
  sdk/typespec/typespec_client_core/src/http/pipeline.rs
Labels: Azure.Core

#2402 Sync eng/common directory with azure-sdk-tools for PR 10134
  eng/common/scripts/Delete-RemoteTag.ps1
  eng/common/scripts/Helpers/git-helpers.ps1
  eng/common/scripts/Helpers/git-helpers.tests.ps1
Labels: EngSys, Central-EngSys
