Repository Azure/azure-sdk-for-rust, pull requests merged in 2025-02, with the labels that each got.

#2058 Sync eng/common directory with azure-sdk-tools for PR 9752
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
Labels: EngSys, Central-EngSys

#2061 Sync eng/common directory with azure-sdk-tools for PR 9698
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/common/pipelines/templates/steps/validate-all-packages.yml
Labels: EngSys, Central-EngSys

#2065 Sync eng/common directory with azure-sdk-tools for PR 9733
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#2054 Sync eng/common directory with azure-sdk-tools for PR 9747
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#2067 Sync eng/common directory with azure-sdk-tools for PR 9745
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2072 Sync eng/common directory with azure-sdk-tools for PR 9781
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2074 Sync eng/common directory with azure-sdk-tools for PR 9764
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#2075 Sync eng/common directory with azure-sdk-tools for PR 9783
  eng/common/TestResources/TestResources-Helpers.ps1
Labels: EngSys, Central-EngSys

#2076 Sync eng/common directory with azure-sdk-tools for PR 9788
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2080 Sync eng/common directory with azure-sdk-tools for PR 9793
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: EngSys, Central-EngSys

#2079 Use MockCredential for recorded test playback
  sdk/core/azure_core_test/src/credential.rs
  sdk/core/azure_core_test/src/lib.rs
  sdk/core/azure_core_test/src/recording.rs
Labels: Azure.Core

#2086 Sync eng/common directory with azure-sdk-tools for PR 9799
  eng/common/scripts/Helpers/Package-Helpers.ps1
Labels: EngSys, Central-EngSys

#2090 Remove default dependencies on ring, webpki-roots
  Cargo.lock
  sdk/core/azure_core/Cargo.toml
  sdk/typespec/typespec_client_core/Cargo.toml
Labels: Azure.Core

#2095 Sync eng/common directory with azure-sdk-tools for PR 9803
  eng/common/scripts/Helpers/Package-Helpers.ps1
Labels: EngSys, Central-EngSys

#2097 Sync eng/common directory with azure-sdk-tools for PR 9810
  eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: EngSys, Central-EngSys

#2098 Sync eng/common directory with azure-sdk-tools for PR 9778
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#2138 Sync eng/common directory with azure-sdk-tools for PR 9807
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#2135 Sync eng/common directory with azure-sdk-tools for PR 9821
  eng/common/pipelines/templates/steps/save-package-properties.yml
Labels: EngSys, Central-EngSys

#1997 Periodically read workload identity token from file
  eng/dict/rust-custom.txt
  sdk/identity/azure_identity/src/credentials/workload_identity_credentials.rs
Labels: blocking-release

#2100 API Review feedback; fixed a bunch of type documentation; reduced type visibility in public API surface.
  sdk/core/azure_core_amqp/examples/connection.rs
  sdk/core/azure_core_amqp/src/fe2o3/messaging/mod.rs
  sdk/core/azure_core_amqp/src/fe2o3/mod.rs
  sdk/core/azure_core_amqp/src/fe2o3/value.rs
  sdk/core/azure_core_amqp/src/lib.rs
  sdk/core/azure_core_amqp/src/messaging.rs
  sdk/core/azure_core_amqp/src/value.rs
  sdk/eventhubs/azure_messaging_eventhubs/README.md
  sdk/eventhubs/azure_messaging_eventhubs/examples/eventhubs_batch_produce_events.rs
  sdk/eventhubs/azure_messaging_eventhubs/examples/eventhubs_consume_events.rs
  sdk/eventhubs/azure_messaging_eventhubs/examples/eventhubs_consume_messages.rs
  sdk/eventhubs/azure_messaging_eventhubs/examples/eventhubs_partition_properties.rs
  sdk/eventhubs/azure_messaging_eventhubs/examples/eventhubs_produce_events.rs
  sdk/eventhubs/azure_messaging_eventhubs/examples/eventhubs_produce_messages.rs
  sdk/eventhubs/azure_messaging_eventhubs/examples/eventhubs_properties.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/common/mod.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/consumer/README.md
  sdk/eventhubs/azure_messaging_eventhubs/src/consumer/event_receiver.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/consumer/mod.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/error.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/lib.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/models/event_data.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/models/mod.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/producer/batch.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/producer/mod.rs
  sdk/eventhubs/azure_messaging_eventhubs/tests/consumer.rs
  sdk/eventhubs/azure_messaging_eventhubs/tests/producer.rs
  sdk/eventhubs/azure_messaging_eventhubs/tests/round_trip.rs
Labels: Azure.Core

#2123 Remove service credentials from DefaultAzureCredential
  eng/dict/rust-custom.txt
  sdk/identity/azure_identity/CHANGELOG.md
  sdk/identity/azure_identity/src/credentials/default_credentials.rs
  sdk/identity/azure_identity/src/timeout.rs
Labels: Azure.Identity, blocking-release

#2145 Add Key Vault keys cryptography tests
  Cargo.lock
  sdk/keyvault/assets.json
  sdk/keyvault/azure_security_keyvault_keys/Cargo.toml
  sdk/keyvault/azure_security_keyvault_keys/README.md
  sdk/keyvault/azure_security_keyvault_keys/tests/key_client.rs
Labels: blocking-release

#2148 Support random number generation for recordings
  Cargo.lock
  Cargo.toml
  eng/dict/crates.txt
  sdk/core/azure_core_test/Cargo.toml
  sdk/core/azure_core_test/README.md
  sdk/core/azure_core_test/src/recording.rs
  sdk/keyvault/azure_security_keyvault_keys/tests/key_client.rs
Labels: Azure.Core, blocking-release

#2155 Update CHANGELOGs for initial release
  sdk/core/azure_core/CHANGELOG.md
  sdk/eventhubs/azure_messaging_eventhubs/CHANGELOG.md
  sdk/identity/azure_identity/CHANGELOG.md
  sdk/keyvault/azure_security_keyvault_keys/CHANGELOG.md
  sdk/keyvault/azure_security_keyvault_secrets/CHANGELOG.md
Labels: Azure.Identity, Azure.Core

#2162 Minor fixes for test proxy on Windows
  sdk/core/azure_core_test/src/lib.rs
  sdk/core/azure_core_test/src/proxy/mod.rs
Labels: Azure.Core

#2170 Update a few READMEs for release
  sdk/core/azure_core_amqp/README.md
  sdk/keyvault/azure_security_keyvault_keys/README.md
Labels: Azure.Core

#2163 Sync eng/common directory with azure-sdk-tools for PR 9834
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: EngSys, Central-EngSys

#2172 Remove HISTORY.md
  HISTORY.md
Labels: Azure.Identity, Azure.Core

#2174 Update azure_core README
  sdk/core/azure_core/README.md
Labels: Azure.Core

#2171 Sync eng/common directory with azure-sdk-tools for PR 9836
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#2180 Fix last_enqueued_time_utc on Linux and other platforms that can represent 1-1-0001 as a SystemTime (but not as an OffsetDateTime).
  sdk/core/azure_core_amqp/src/fe2o3/value.rs
Labels: Azure.Core

#2182 Update azure_core README samples
  Cargo.lock
  sdk/core/azure_core/Cargo.toml
  sdk/core/azure_core/README.md
  sdk/core/azure_core/src/lib.rs
  sdk/core/azure_core_amqp/src/lib.rs
Labels: Azure.Core

#2203 Sync eng/common directory with azure-sdk-tools for PR 9862
  eng/common/scripts/Helpers/Package-Helpers.ps1
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2200 remove async-std and replace with tokio/futures
  Cargo.lock
  Cargo.toml
  sdk/core/azure_core_amqp/Cargo.toml
  sdk/core/azure_core_amqp/src/fe2o3/cbs.rs
  sdk/core/azure_core_amqp/src/fe2o3/connection.rs
  sdk/core/azure_core_amqp/src/fe2o3/management.rs
  sdk/core/azure_core_amqp/src/fe2o3/messaging/mod.rs
  sdk/core/azure_core_amqp/src/fe2o3/receiver.rs
  sdk/core/azure_core_amqp/src/fe2o3/sender.rs
  sdk/core/azure_core_amqp/src/fe2o3/session.rs
  sdk/core/azure_core_amqp/src/noop.rs
  sdk/core/azure_core_amqp/src/receiver.rs
  sdk/core/azure_core_amqp/src/sender.rs
  sdk/eventhubs/azure_messaging_eventhubs/Cargo.toml
  sdk/eventhubs/azure_messaging_eventhubs/README.md
  sdk/eventhubs/azure_messaging_eventhubs/src/consumer/README.md
  sdk/eventhubs/azure_messaging_eventhubs/src/consumer/event_receiver.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/consumer/mod.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/producer/batch.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/producer/mod.rs
  sdk/eventhubs/azure_messaging_eventhubs/tests/consumer.rs
  sdk/eventhubs/azure_messaging_eventhubs/tests/round_trip.rs
  sdk/keyvault/azure_security_keyvault_secrets/Cargo.toml
Labels: Azure.Core, Community Contribution, customer-reported

#2212 Sync eng/common directory with azure-sdk-tools for PR 9896
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2156 Optimize rebuild when AZURE_TEST_MODE changes
  sdk/core/azure_core_test/build.rs
Labels: Azure.Core

#2209 Fix broken README links
  README.md
  sdk/identity/azure_identity/README.md
Labels: Azure.Identity

#2214 Enable tracing of HTTP error bodies
  sdk/core/azure_core/Cargo.toml
  sdk/typespec/typespec_client_core/Cargo.toml
  sdk/typespec/typespec_client_core/src/error/http_error.rs
Labels: Azure.Core

#2215 Sync eng/common directory with azure-sdk-tools for PR 9895
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#2216 Sync eng/common directory with azure-sdk-tools for PR 9901
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#2218 Create assets.json in crate directory if needed
  sdk/core/azure_core_test/examples/test_proxy.rs
  sdk/core/azure_core_test/src/lib.rs
  sdk/core/azure_core_test/src/proxy/mod.rs
  sdk/core/azure_core_test/src/recorded.rs
Labels: Azure.Core

#2217 Import the right features for HTTP-based crates
  .taplo.toml
  Cargo.toml
  sdk/core/azure_core/Cargo.toml
  sdk/core/azure_core_amqp/Cargo.toml
  sdk/core/azure_core_test/src/lib.rs
  sdk/core/azure_core_test/src/proxy/client.rs
  sdk/core/azure_core_test/src/proxy/mod.rs
  sdk/core/azure_core_test/src/proxy/policy.rs
  sdk/core/azure_core_test/src/recorded.rs
  sdk/cosmos/azure_data_cosmos/Cargo.toml
  sdk/cosmos/azure_data_cosmos/tests/framework/mod.rs
  sdk/cosmos/azure_data_cosmos/tests/framework/test_account.rs
  sdk/eventhubs/azure_messaging_eventhubs/Cargo.toml
  sdk/keyvault/assets.json
  sdk/typespec/typespec_client_core/Cargo.toml
Labels: Cosmos, Azure.Core

#2227 Sync eng/common directory with azure-sdk-tools for PR 9902
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2234 [Cosmos] changelog updates for 0.22.0 release
  sdk/cosmos/azure_data_cosmos/CHANGELOG.md
Labels: Cosmos

#2236 [Cosmos] reduce azure_data_cosmos to 5 keywords
  sdk/cosmos/azure_data_cosmos/Cargo.toml
Labels: Cosmos

#2238 Increment versions for cosmos releases
  Cargo.lock
  sdk/cosmos/azure_data_cosmos/CHANGELOG.md
  sdk/cosmos/azure_data_cosmos/Cargo.toml
Labels: Cosmos

#2226 First attempt at "rationalizing" AMQP error codes.
  Cargo.lock
  Cargo.toml
  sdk/core/azure_core_amqp/.dict.txt
  sdk/core/azure_core_amqp/Cargo.toml
  sdk/core/azure_core_amqp/src/connection.rs
  sdk/core/azure_core_amqp/src/error.rs
  sdk/core/azure_core_amqp/src/fe2o3/cbs.rs
  sdk/core/azure_core_amqp/src/fe2o3/connection.rs
  sdk/core/azure_core_amqp/src/fe2o3/error.rs
  sdk/core/azure_core_amqp/src/fe2o3/management.rs
  sdk/core/azure_core_amqp/src/fe2o3/receiver.rs
  sdk/core/azure_core_amqp/src/fe2o3/sender.rs
  sdk/core/azure_core_amqp/src/fe2o3/session.rs
  sdk/core/azure_core_amqp/src/fe2o3/value.rs
  sdk/core/azure_core_amqp/src/lib.rs
  sdk/core/azure_core_amqp/src/messaging.rs
  sdk/core/azure_core_amqp/src/noop.rs
  sdk/core/azure_core_amqp/src/sender.rs
  sdk/core/azure_core_amqp/src/value.rs
  sdk/eventhubs/.dict.txt
  sdk/eventhubs/azure_messaging_eventhubs/CHANGELOG.md
  sdk/eventhubs/azure_messaging_eventhubs/src/common/mod.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/consumer/mod.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/error.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/producer/batch.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/producer/mod.rs
  sdk/eventhubs/azure_messaging_eventhubs/tests/consumer.rs
  sdk/typespec/Cargo.toml
  sdk/typespec/src/error/mod.rs
Labels: Azure.Core

#2244 Sync eng/common directory with azure-sdk-tools for PR 9921
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#2229 Sync eng/common directory with azure-sdk-tools for PR 9888
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2250 Sync eng/common directory with azure-sdk-tools for PR 9917
  eng/common/pipelines/templates/steps/detect-api-changes.yml
Labels: EngSys, Central-EngSys

#2245 Enable Custom Endpoints for EventHubs
  .vscode/cspell.json
  Cargo.lock
  sdk/core/azure_core_amqp/Cargo.toml
  sdk/core/azure_core_amqp/src/connection.rs
  sdk/core/azure_core_amqp/src/fe2o3/cbs.rs
  sdk/core/azure_core_amqp/src/fe2o3/connection.rs
  sdk/core/azure_core_amqp/src/fe2o3/management.rs
  sdk/core/azure_core_amqp/src/fe2o3/messaging/message_fields.rs
  sdk/core/azure_core_amqp/src/fe2o3/receiver.rs
  sdk/core/azure_core_amqp/src/fe2o3/sender.rs
  sdk/core/azure_core_amqp/src/fe2o3/session.rs
  sdk/core/azure_core_amqp/src/fe2o3/value.rs
  sdk/core/azure_core_amqp/src/lib.rs
  sdk/core/azure_core_amqp/src/messaging.rs
  sdk/core/azure_core_amqp/src/value.rs
  sdk/eventhubs/azure_messaging_eventhubs/Cargo.toml
  sdk/eventhubs/azure_messaging_eventhubs/examples/eventhubs_batch_produce_events.rs
  sdk/eventhubs/azure_messaging_eventhubs/examples/eventhubs_produce_events.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/common/connection_manager.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/common/mod.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/consumer/mod.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/error.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/lib.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/models/mod.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/producer/batch.rs
  sdk/eventhubs/azure_messaging_eventhubs/src/producer/mod.rs
  sdk/eventhubs/azure_messaging_eventhubs/tests/consumer.rs
  sdk/eventhubs/azure_messaging_eventhubs/tests/producer.rs
Labels: Azure.Core
